### PR TITLE
add --semantic flag

### PR DESCRIPTION
**Pull request by perennialmind**
Like --final, --semantic compensates for differing platform conventions
regarding termination of the last line in a file. In contrast,
--semantic aims to preserve logical lines across representations.
This assumes windows conventions use CRLF as line separators, not terminators.
An equivalent formulation: lines are terminated by exactly one of CRLF or EOF.
Yet another: CRLF always starts a new line, even at file end.

The goal is to cope with the unterminated-line problem in a way that
allows lossless round-trips. In concept, git smudge and clean filters are
intended to be the inverse of one another, making changes that are fully
reversible. Adding a trailing blank line to a windows file is normally
inoffensive, but can be a nuisance in the presence of change-tracking.

### CODE REVIEW

**Comment by mdolidon** [comment]
Hello @perennialmind. Thanks a lot for your work, this is an interesting idea ! To be honest, I didn't even have the notion of Window's last char not being an EOL, vs Linux's well known convention.

I'll merge the pull request. But if you'll allow, I'll take some time to review it with a cold head. I've got a newborn child at home and, besides office time, moments for full concentration are rare and short for now. Allow a few days.

With my best regards.

**Comment by perennialmind** [comment]
Hello @mdolidon. Wow - congratulations! And, obviously you have more important things to which to attend. I just wanted to share back the bits that were useful to me.

As you say, the unix conventions are explicit and set in stone, baked into C and POSIX. I think that the windows conventions are much looser. I take Notepad and Visual Studio to be authoritative, but as far as I can tell, the pattern extends to Windows-native plaintext editors in general. I've seen it attributed to a historical disregard for trailing whitespace, going back to the infinite-character-grid model of some early DOS editors.

Anyway, thanks for giving it a look. I won't be offended if it turns out not to be something you want to merge. Most folks seem to want exactly the approach you already had. EditorConfig even codified the practice with `insert_final_newline`, and they seem to have pretty solid uptake.

Let me know if there's anything you'd like changed. The option name, at least, could probably be improved.

P.S. I pushed a second commit that looks a little cleaner to my eye and behaves sanely with `--final`.

**Comment by mdolidon** [comment]
Hello perennialmind.

After lots and lots of changes and events in private and professional life over six months, I'm finally slowly coming back to Github.

I've been looking a little bit into this. It seems that the presence or absence of a final EOL in Windows is not really something that anybody really knows about, and therefore would want to enforce. As such, ,I have the feeling that this would eventually be a rather obscure option. I'd like to keep this software very simple and immediately understandable. That was part of the reason why I wrote it. :)

Therefore I think that I will not follow up on the pull request. However, I'd like to thank you for taking the time to share what you adapted !

Mathias

**Comment by perennialmind** [comment]
And I thought making it conditional would *help* the odds of inclusion, but yeah, it just makes it more complicated. Doh. 🤦‍♂️

I'll probably end up maintaining the fork for my own needs. Dealing with "whitespace errors" in git can be gnarly. I completely agree that Windows apps aren't picky. It's all in the friction when the two worlds meet.

In which case, I'll drop the flag and just do it the "right" way. 😁

**Pull request closed without merging**
